# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.3
loader_version=0.19.5

# Fabric API
fabric_version=0.160.5+26.3
# Polymer
polymer_version=0.18.2+26.3
# Server-Translations https://github.com/NucleoidMC/Server-Translations
server_translations_api_version=3.2.0+26.3
# Fantasy https://github.com/NucleoidMC/fantasy
fantasy_version=0.8.4+26.3
# Fabric Permissions API https://github.com/lucko/fabric-permissions-api
fabric_permissions_api_version=0.7.0
# Map templates https://github.com/NucleoidMC/map-templates
map_templates_version=0.3.2+26.2

# Mod Properties
mod_version=0.2.5+26.3
maven_group=xyz.nucleoid
archives_base_name=nucleoid-creator-tools
