# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G

minecraft_version=26.1.2
loader_version=0.19.2

# Fabric API
fabric_version=0.146.1+26.1.2
# Polymer
polymer_version=0.16.3+26.1.2
# Server-Translations https://github.com/NucleoidMC/Server-Translations
server_translations_api_version=3.0.3+26.1
# Fantasy https://github.com/NucleoidMC/fantasy
fantasy_version=0.8.0-beta.1+26.1.1
# Fabric Permissions API https://github.com/lucko/fabric-permissions-api
fabric_permissions_api_version=0.7.0
# Map templates https://github.com/NucleoidMC/map-templates
map_templates_version=0.3.0+26.1

# Mod Properties
mod_version=0.2.3+26.1.2
maven_group=xyz.nucleoid
archives_base_name=nucleoid-creator-tools
